
FROM sebp/elk

WORKDIR ${LOGSTASH_HOME}
RUN gosu logstash bin/logstash-plugin install logstash-input-rss

#ADD ./logstash/pipeline/logstash.conf /etc/logstash/conf.d/30-output.conf
#ADD ./kibana/config/kibana.yml /opt/kibana/config/kibana.yml
#ADD ./logstash/config/logstash.yml /opt/logstash/config/logstash.yml
#ADD ./elasticsearch/config/elasticsearch.yml /opt/elasticsearch/config/elasticsearch.yml

RUN curl -L -O https://artifacts.elastic.co/downloads/apm-server/apm-server-7.6.1-amd64.deb
RUN dpkg -i apm-server-7.6.1-amd64.deb
RUN service apm-server start

EXPOSE 8200 9200 5044 5601

