---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.infra.sources.default.logAlias: logstash-*,default-logs-*,filebeat-*,kibana_sample_data_logs*
xpack.infra.sources.default.metricAlias: logstash-*,metricbeat-*

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme
